### ISSUE TITLE
AIA: contradiction in bits 12:0 of hvip description

### ISSUE THREAD

**Issue by evgeniy-paltsev** [riscv/riscv-aia#93]
The current AIA documentation has a contradiction in a part describing bits 12:0 of `hvip`:

> Bits 12:0 of `hvip` are reserved and must be read-only zeros, while bits 12:0 of `hvip` are defined by the RISC-V Privileged Architecture. Specifically, bits 10, 6, and 2 of `hvip` are writable bits...
>> From chapter `6.3.2. Virtual interrupts for VS level`

We specify (without any condition) that 12:0 bits of hvip are read-only zeros and writable at a same time.
It seems to be a typo and the first part of phrase could be about `hvien` instead of `hvip`. So, proper phrasing could be:

> Bits 12:0 of **_hvien_** are reserved and must be read-only zeros

Could you please confirm if it is just a typo or I misunderstand the phrasing in the docs?

**Comment by jhauser-us** [comment]
The document you are looking at is the one generated from the AsciiDoc sources, which still contain many errors.  In my opinion, it should never have been released as the "correct" version, because it's often not correct.  I just deleted that ill-advised release.

Please discard the file you have.  You can obtain the specification that was actually ratified here:
https://github.com/riscv/riscv-aia/releases/tag/1.0

Eventually, the AsciiDoc version will be made to match the ratified specification, but it's not there yet.

**Comment by evgeniy-paltsev** [comment]
Marking as closed as the problematic release was removed.
